# Generated by Django 5.2 on 2025-04-23 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('subjects_of_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=100)),
                ('preferred_experience', models.PositiveIntegerField(default=0, help_text='Preferred years of experience')),
                ('budget_range', models.CharField(blank=True, max_length=100, null=True)),
                ('location_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=15)),
                ('requirements_met', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_bid_cycle', models.PositiveIntegerField(default=1)),
                ('max_bids_current_cycle', models.PositiveIntegerField(default=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='student.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTeacherContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('coins_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='student.jobpost')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_contacts', to='student.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_contacts', to='teacher.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(max_length=255)),
                ('similarity_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='student.jobpost')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='teacher.teacherprofile')),
            ],
            options={
                'ordering': ['-similarity_score', 'created_at'],
                'unique_together': {('job_post', 'teacher')},
            },
        ),
    ]
